/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aryaa
 */
public class PENTINGWARUNG extends javax.swing.JFrame {
    int Jumlah;
    int Total;
    

    /**
     * Creates new form PENTINGWARUNG
     */
    public PENTINGWARUNG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fjumlahbeli = new javax.swing.JLabel();
        fareabeli = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnplus = new javax.swing.JButton();
        btnminus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnbeli = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fpesan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ftotal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        frawon = new javax.swing.JRadioButton();
        fsoto = new javax.swing.JRadioButton();
        fmieayam = new javax.swing.JRadioButton();
        fnasigoreng = new javax.swing.JRadioButton();
        fbakso = new javax.swing.JRadioButton();
        fsate = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WARUNG AKHIRAT");
        jPanel4.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(new java.awt.GridLayout(6, 0, 4, 0));

        fjumlahbeli.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        fjumlahbeli.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fjumlahbeli.setText("JUMLAH BELI");
        jPanel2.add(fjumlahbeli);

        fareabeli.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        fareabeli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fareabeli.setText("0");
        jPanel2.add(fareabeli);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnplus.setBackground(new java.awt.Color(255, 51, 51));
        btnplus.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnplus.setText("+");
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });
        jPanel3.add(btnplus);

        btnminus.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnminus.setText("-");
        btnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminusActionPerformed(evt);
            }
        });
        jPanel3.add(btnminus);

        jPanel2.add(jPanel3);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INFORMASI PESAN");
        jPanel2.add(jLabel3);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnbeli.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnbeli.setText("BELI");
        btnbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeliActionPerformed(evt);
            }
        });
        jPanel5.add(btnbeli);

        btnhapus.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel5.add(btnhapus);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 255, 255));
        jPanel6.setLayout(new java.awt.GridLayout(3, 6, 5, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setText("PESANAN ANDA");
        jPanel6.add(jLabel4);

        fpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpesanActionPerformed(evt);
            }
        });
        jPanel6.add(fpesan);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setText("JUMLAH HARGA");
        jPanel6.add(jLabel5);

        fharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhargaActionPerformed(evt);
            }
        });
        jPanel6.add(fharga);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setText("TOTAL PESAN");
        jPanel6.add(jLabel6);
        jPanel6.add(ftotal);

        jPanel2.add(jPanel6);

        jPanel4.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setLayout(new java.awt.GridLayout(4, 0, 0, -100));

        menu.add(frawon);
        frawon.setText("Rawon");
        jPanel1.add(frawon);

        menu.add(fsoto);
        fsoto.setText("Soto");
        jPanel1.add(fsoto);

        menu.add(fmieayam);
        fmieayam.setText("Mie Ayam");
        jPanel1.add(fmieayam);

        menu.add(fnasigoreng);
        fnasigoreng.setText("Nasi Goreng");
        jPanel1.add(fnasigoreng);

        menu.add(fbakso);
        fbakso.setText("Bakso");
        jPanel1.add(fbakso);

        menu.add(fsate);
        fsate.setText("Sate");
        jPanel1.add(fsate);

        jPanel4.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        // TODO add your handling code here:
        Jumlah = Integer.parseInt(fareabeli.getText());
        if(Jumlah >= 0){
            Jumlah = Jumlah + 1;
            fareabeli.setText(Integer.toString(Jumlah));
        }
    }//GEN-LAST:event_btnplusActionPerformed

    private void btnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminusActionPerformed
        // TODO add your handling code here:
        Jumlah = Integer.parseInt(fareabeli.getText());
        if (Jumlah > 0) {
            Jumlah = Jumlah - 1;
            fareabeli.setText(Integer.toString(Jumlah));
    }
    }//GEN-LAST:event_btnminusActionPerformed

    private void fpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpesanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_fpesanActionPerformed

    private void fhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhargaActionPerformed
        // TODO add your handling code here:             
    }//GEN-LAST:event_fhargaActionPerformed

    private void btnbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeliActionPerformed
        // TODO add your handling code here:
          if (frawon.isSelected()){
        fpesan.setText("Rawon");
        fharga.setText("Rp 20.000");
            Total = Jumlah * 20000;
            ftotal.setText(Integer.toString(Total));
    } else if (fsoto.isSelected()) {
        fpesan.setText("soto");
        fharga.setText("Rp 10.000");
            Total = Jumlah * 10000;
             ftotal.setText(Integer.toString(Total));
    } else if (fmieayam.isSelected()) {
        fpesan.setText("mieayam");
        fharga.setText("Rp 15.000");
            Total = Jumlah * 15000;
             ftotal.setText(Integer.toString(Total));
    } else if (fnasigoreng.isSelected()) {
        fpesan.setText("nasigoreng");
        fharga.setText("Rp 15.000");
            Total = Jumlah * 15000;
             ftotal.setText(Integer.toString(Total));
    } else if (fbakso.isSelected()) {
        fpesan.setText("bakso");
        fharga.setText("Rp 10.000");
            Total = Jumlah * 10000;
             ftotal.setText(Integer.toString(Total));
    } else if (fsate.isSelected()) {
        fpesan.setText("sate");
        fharga.setText("Rp 25.000");
            Total = Jumlah * 25000;
             ftotal.setText(Integer.toString(Total));
    } else {
        // Tidak ada radio button yang dipilih
        fpesan.setText("Pilih menu terlebih dahulu");
}

    }//GEN-LAST:event_btnbeliActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        fpesan.setText("");
        fharga.setText("");
        ftotal.setText("");
        menu.clearSelection();
        fareabeli.setText("0");
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PENTINGWARUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PENTINGWARUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PENTINGWARUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PENTINGWARUNG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PENTINGWARUNG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbeli;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnminus;
    private javax.swing.JButton btnplus;
    private javax.swing.JTextField fareabeli;
    private javax.swing.JRadioButton fbakso;
    private javax.swing.JTextField fharga;
    private javax.swing.JLabel fjumlahbeli;
    private javax.swing.JRadioButton fmieayam;
    private javax.swing.JRadioButton fnasigoreng;
    private javax.swing.JTextField fpesan;
    private javax.swing.JRadioButton frawon;
    private javax.swing.JRadioButton fsate;
    private javax.swing.JRadioButton fsoto;
    private javax.swing.JTextField ftotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.ButtonGroup menu;
    // End of variables declaration//GEN-END:variables
}
