/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aryaa
 */
public class UPAHKARYAWAN extends javax.swing.JFrame {

    /**
     * Creates new form UPAHKARYAWAN
     */
    public UPAHKARYAWAN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fjumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ftarif = new javax.swing.JTextField();
        btngajiboruto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fgajiboruto = new javax.swing.JTextField();
        btnhitunggajibersih = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fgajibersih = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("GAJI KARYAWAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 230, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Jumlah Kerja 1Minggu");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 170, 20);

        fjumlah.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fjumlah);
        fjumlah.setBounds(20, 110, 150, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("Tarif Per-jam");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 60, 100, 19);

        ftarif.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(ftarif);
        ftarif.setBounds(410, 90, 140, 22);

        btngajiboruto.setBackground(new java.awt.Color(102, 153, 255));
        btngajiboruto.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btngajiboruto.setText("Hitung Gaji Boruto");
        btngajiboruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngajiborutoActionPerformed(evt);
            }
        });
        getContentPane().add(btngajiboruto);
        btngajiboruto.setBounds(20, 170, 170, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Gaji Boruto");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 230, 100, 19);

        fgajiboruto.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fgajiboruto);
        fgajiboruto.setBounds(130, 230, 150, 22);

        btnhitunggajibersih.setBackground(new java.awt.Color(102, 153, 255));
        btnhitunggajibersih.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnhitunggajibersih.setText("Hitung Gaji Bersih");
        btnhitunggajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitunggajibersihActionPerformed(evt);
            }
        });
        getContentPane().add(btnhitunggajibersih);
        btnhitunggajibersih.setBounds(0, 280, 163, 26);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Gaji Bersih");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 340, 80, 19);

        fgajibersih.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(fgajibersih);
        fgajibersih.setBounds(10, 380, 140, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aryaa\\OneDrive\\Documents\\SEM 3\\PEMVIS\\bg.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, 0, 630, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngajiborutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngajiborutoActionPerformed
        // TODO add your handling code here:
         double jamKerja = Double.parseDouble(fjumlah.getText());
        double tarifPerJam = Double.parseDouble(ftarif.getText());
        
        double gajiBoruto;
        
        if (jamKerja <= 40) {
            gajiBoruto = jamKerja * tarifPerJam;
        } else {
            double jamLembur = jamKerja - 40;
            gajiBoruto = (40 * tarifPerJam) + (jamLembur * tarifPerJam * 1.5);
        }
        
        fgajiboruto.setText(String.valueOf(gajiBoruto));
    }//GEN-LAST:event_btngajiborutoActionPerformed

    private void btnhitunggajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitunggajibersihActionPerformed
        // TODO add your handling code here:
         double gajiBoruto = Double.parseDouble(fgajiboruto.getText());
        double pajak = 0.1 * gajiBoruto;
        double gajiBersih = gajiBoruto - pajak;
        fgajibersih.setText(String.valueOf(gajiBersih));
    }//GEN-LAST:event_btnhitunggajibersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UPAHKARYAWAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UPAHKARYAWAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UPAHKARYAWAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UPAHKARYAWAN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPAHKARYAWAN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngajiboruto;
    private javax.swing.JButton btnhitunggajibersih;
    private javax.swing.JTextField fgajibersih;
    private javax.swing.JTextField fgajiboruto;
    private javax.swing.JTextField fjumlah;
    private javax.swing.JTextField ftarif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
